# Generated by Django 4.2.24 on 2025-09-26 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_tabla_menu_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación'),
        ),
    ]
