# Generated by Django 4.2.24 on 2025-09-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_fix_tabla_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icono',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Icono'),
        ),
    ]
