# Generated by Django 4.2.24 on 2025-09-26 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0004_model_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to='noticias/miniaturas/')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=400, verbose_name='Descripción de la noticia')),
                ('cuerpo', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hoja_estilo', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='noticias.categoria')),
            ],
            options={
                'ordering': ['-fecha_publicacion', '-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_publicacion'], name='noticias_no_fecha_p_e1f6cb_idx'), models.Index(fields=['titulo'], name='noticias_no_titulo_a558a3_idx')],
            },
        ),
    ]
