# Generated by Django 4.2.24 on 2025-09-27 19:21

from django.db import migrations, models
import usuarios.managers.usuario_manager


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.managers.usuario_manager.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
